// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Televizor.VolgaIronHack.Entities;

#nullable disable

namespace Televizor.VolgaIronHack.Entities.Migrations
{
    [DbContext(typeof(VolgaIronHackDbContext))]
    [Migration("20211120182419_RailwaySchedule")]
    partial class RailwaySchedule
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Televizor.VolgaIronHack.Entities.DeliveryRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("DeliveryRequests");
                });

            modelBuilder.Entity("Televizor.VolgaIronHack.Entities.Parcel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeliveryDeadLine")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinationStationExpressId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("InitiatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceStationExpressId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Parcels");
                });

            modelBuilder.Entity("Televizor.VolgaIronHack.Entities.ParcelDeliveryStage", b =>
                {
                    b.Property<Guid>("ParcelId")
                        .HasColumnType("uuid");

                    b.Property<long>("SerialId")
                        .HasColumnType("bigint");

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParcelId1")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParcelId2")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ParcelId", "SerialId");

                    b.HasIndex("ParcelId1");

                    b.HasIndex("ParcelId2");

                    b.ToTable("ParcelDeliveryStage");
                });

            modelBuilder.Entity("Televizor.VolgaIronHack.Entities.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExpressId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExpressName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("Televizor.VolgaIronHack.Entities.TrainRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExpressId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TrainRoutes");
                });

            modelBuilder.Entity("Televizor.VolgaIronHack.Entities.TrainRouteStop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("MoscowArriveTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("MoscowDepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("StopTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("TrainRouteId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TrainRouteId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrainRouteId");

                    b.HasIndex("TrainRouteId1");

                    b.ToTable("TrainRouteStops");
                });

            modelBuilder.Entity("Televizor.VolgaIronHack.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Televizor.VolgaIronHack.Entities.ParcelDeliveryStage", b =>
                {
                    b.HasOne("Televizor.VolgaIronHack.Entities.Parcel", "Parcel")
                        .WithMany()
                        .HasForeignKey("ParcelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Televizor.VolgaIronHack.Entities.Parcel", null)
                        .WithMany("Stages")
                        .HasForeignKey("ParcelId1");

                    b.HasOne("Televizor.VolgaIronHack.Entities.Parcel", null)
                        .WithMany()
                        .HasForeignKey("ParcelId2");

                    b.Navigation("Parcel");
                });

            modelBuilder.Entity("Televizor.VolgaIronHack.Entities.TrainRouteStop", b =>
                {
                    b.HasOne("Televizor.VolgaIronHack.Entities.TrainRoute", null)
                        .WithMany("Stops")
                        .HasForeignKey("TrainRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Televizor.VolgaIronHack.Entities.TrainRoute", null)
                        .WithMany()
                        .HasForeignKey("TrainRouteId1");
                });

            modelBuilder.Entity("Televizor.VolgaIronHack.Entities.Parcel", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("Televizor.VolgaIronHack.Entities.TrainRoute", b =>
                {
                    b.Navigation("Stops");
                });
#pragma warning restore 612, 618
        }
    }
}
