// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Televizor.VolgaIronHack.Entities;

#nullable disable

namespace Televizor.VolgaIronHack.Entities.Migrations
{
    [DbContext(typeof(VolgaIronHackDbContext))]
    [Migration("20211120163749_ParcelDeliveryStage")]
    partial class ParcelDeliveryStage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Televizor.VolgaIronHack.Entities.Parcel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("InitiatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Parcels");
                });

            modelBuilder.Entity("Televizor.VolgaIronHack.Entities.ParcelDeliveryStage", b =>
                {
                    b.Property<Guid>("ParcelId")
                        .HasColumnType("uuid");

                    b.Property<long>("SerialId")
                        .HasColumnType("bigint");

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<Guid>("ParcelId1")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ParcelId", "SerialId");

                    b.HasIndex("ParcelId1");

                    b.ToTable("ParcelDeliveryStage");
                });

            modelBuilder.Entity("Televizor.VolgaIronHack.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Televizor.VolgaIronHack.Entities.ParcelDeliveryStage", b =>
                {
                    b.HasOne("Televizor.VolgaIronHack.Entities.Parcel", null)
                        .WithMany("Stages")
                        .HasForeignKey("ParcelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Televizor.VolgaIronHack.Entities.Parcel", "Parcel")
                        .WithMany()
                        .HasForeignKey("ParcelId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parcel");
                });

            modelBuilder.Entity("Televizor.VolgaIronHack.Entities.Parcel", b =>
                {
                    b.Navigation("Stages");
                });
#pragma warning restore 612, 618
        }
    }
}
